### ISSUE TITLE
Proposal default > ini > env > cmd

### ISSUE THREAD

**Issue by arkanoid87** [juancarlospaco/cliche#10]
it would be nice to extend current behaviour to ini file > env variables > cmdline (usually in this order) like many Go programs do, and also many modern containerizable application

for example if I would have

cliche variables
```nim
commandLineParams().getOpt (myoption: 12)
```
myproject.ini file with
```ini
myoption=22
```
env set with
```env
MYPROJECT_MYOPTION=32
```
cmdline with
```
--myoption=42
```

At runtime I'd get
```nim
echo myoption
# 42
```
due to `default > ini > env > cmd` order

Basically given existing `variables` block, it can be re-used to read ini file and environment variables (using custom prefix) and finally set the variable according to a certain order

**Comment by juancarlospaco** [comment]
Maybe somehow integrate https://juancarlospaco.github.io/nodejs/nodejs/jsdotenv#typeminussafe-dotenv-for-nim-optimized-for-javascript

**Comment by juancarlospaco** [comment]
Fixed, using `useEnvVars=true` should try to read from env vars, you may need to `import std/envvars`.
* static default :arrow_right: env var :arrow_right: command line

**Comment by arkanoid87** [comment]
just realized that "NIM_" & key.toUpperAscii" vars are read only if the same var is also submitted as command line argument.
The expected behaviour would be to use env instead of cli here, not as a way to override cli
