### ISSUE TITLE
Boolean literals aren't valid values

### ISSUE THREAD

**Issue by hochata** [juancarlospaco/cliche#2]
Using `true` or `false` as tuple value results in undeclared variables.

# Example

```nim
import std/strutils
import cliche

@["--a=true"].getOpt (a: false)

echo a
```

results in a compilation error `Error: undeclared indentifier 'a'`

**Comment by juancarlospaco** [comment]
This is kinda duplicate of #3 

Even if it is not exactly the same, the reason behind is the same as #3 
it is a limitation of the Nim macro system, we are kinda near the limit of the macro system,
so I am closing this as duplicate, because they are the same bug behind.
