### ISSUE TITLE
Can't use constants as values

### ISSUE THREAD

**Issue by hochata** [juancarlospaco/cliche#3]
It seems values are limited to literal values, even though constant are also static values 

# Example

The following code

```nim
import std/strutils
import cliche

const val = 0

@["--a=1"].getOpt (a: val)

echo a
```
results in `Error: undeclared identifier: 'a'`

**Comment by juancarlospaco** [comment]
Constants as default values:

```nim
const x = 0
template z(): auto = x
@["--a=1"].getOpt (a: z())
echo a
```

This is something in Nim macro system itself, but just using a `template` it works Ok,
just make a template that returns the value and it will work. 
🙂

**Comment by juancarlospaco** [comment]
I do not think this bug is fixable by any other way than this workaround.
