### ISSUE TITLE
Can´t parse `uint64` and `float32`

### ISSUE THREAD

**Issue by hochata** [juancarlospaco/cliche#5]
For some types the parsing procedures are wrong.

# Examples

## `uint64`

It is parsed as an `int`, so the following code

```nim
@["--a=18446744073709551615"].getOpt (a: 0u64)
```

results in `Parsed integer outside of valid range [ValueError]`

## `float32`

It is parsed as an `int`,

```nim
@["--b=1.0"].getOpt (b: 0f32)
```

results in `invalid integer: 1.0 [ValueError]`

**Comment by juancarlospaco** [comment]
Fixed by https://github.com/juancarlospaco/cliche/pull/6
