### ISSUE TITLE
[Feature request] Parse bool

### ISSUE THREAD

**Issue by arkanoid87** [juancarlospaco/cliche#8]
I've switched from cligen to cliche and all is good, except that I had to switch from `--enableFeature=true` to `--enableFeature=yes|true|Yes|True` adding some boilerplate code

Would be nice to add bools too!

**Comment by juancarlospaco** [comment]
Use `char`, like `--enableFeature=y` ?.

It is the way `bool` is implemented in Nim, it is actually an `int`, `0` for `false` and `1` for `true`.

Can you provide some small example code that reproduces what you want do do?.

**Comment by arkanoid87** [comment]
tried a PR here https://github.com/juancarlospaco/cliche/pull/9

**Comment by juancarlospaco** [comment]
Should be working now!, otherwise reopen plz.
What are you building?, share if its public code.
:slightly_smiling_face:
